# Generated by Django 4.2.3 on 2025-02-01 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Locker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locker_number", models.IntegerField(unique=True)),
                ("is_using", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="LockerOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="가격"
                    ),
                ),
                ("order_start_date", models.DateTimeField(verbose_name="대여 시작일")),
                ("order_end_date", models.DateTimeField(verbose_name="대여 종료일")),
                (
                    "rental_period",
                    models.IntegerField(verbose_name="대여 기간(일 단위)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "주문요청"),
                            ("failed_payment", "결제실패"),
                            ("paid", "결제완료"),
                            ("prepared_product", "상품준비중"),
                            ("shipped", "배송중"),
                            ("delivered", "배송완료"),
                            ("cancelled", "주문취소"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=20,
                        verbose_name="진행상태",
                    ),
                ),
                (
                    "locker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locker.locker",
                        verbose_name="락커",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="유저",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LockerOrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        default=dict, editable=False, verbose_name="포트원 결제내역"
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="쇼핑몰 결제식별자",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="결제명")),
                (
                    "desired_amount",
                    models.PositiveIntegerField(
                        editable=False, verbose_name="결제금액"
                    ),
                ),
                (
                    "buyer_name",
                    models.CharField(
                        editable=False, max_length=100, verbose_name="구매자 이름"
                    ),
                ),
                (
                    "buyer_email",
                    models.EmailField(
                        editable=False, max_length=254, verbose_name="구매자 이메일"
                    ),
                ),
                (
                    "pay_method",
                    models.CharField(
                        choices=[("card", "신용카드")],
                        default="card",
                        max_length=20,
                        verbose_name="결제수단",
                    ),
                ),
                (
                    "pay_status",
                    models.CharField(
                        choices=[
                            ("ready", "결제 준비"),
                            ("paid", "결제 완료"),
                            ("cancelled", "결제 취소"),
                            ("failed", "결제 실패"),
                        ],
                        default="ready",
                        max_length=20,
                        verbose_name="결제상태",
                    ),
                ),
                (
                    "is_paid_ok",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name="결제성공 여부",
                    ),
                ),
                (
                    "locker_order",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locker.lockerorder",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
