# Generated by Django 4.2.3 on 2025-02-01 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locker", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lockerorder",
            old_name="price",
            new_name="order_price",
        ),
        migrations.RenameField(
            model_name="lockerorder",
            old_name="user",
            new_name="order_user",
        ),
    ]
