# Generated by Django 4.2.3 on 2025-02-01 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locker", "0002_rename_price_lockerorder_order_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lockerorder",
            name="order_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 2, 1, 14, 11, 5, 988879, tzinfo=datetime.timezone.utc
                ),
                verbose_name="주문날짜",
            ),
            preserve_default=False,
        ),
    ]
