# Generated by Django 4.2.3 on 2025-03-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locker", "0003_lockerorder_order_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="lockerorder",
            name="is_using",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lockerorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "주문요청"),
                    ("failed_payment", "결제실패"),
                    ("paid", "결제완료"),
                    ("prepared_product", "상품준비중"),
                    ("shipped", "배송중"),
                    ("delivered", "배송완료"),
                    ("inservice", "서비스이용중"),
                    ("outservice", "서비스종료"),
                    ("cancelled", "주문취소"),
                ],
                db_index=True,
                default="requested",
                max_length=20,
                verbose_name="진행상태",
            ),
        ),
    ]
