# Generated by Django 4.2.3 on 2025-03-01 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locker", "0005_remove_lockerorder_is_using_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lockerorder",
            old_name="locket_status",
            new_name="locker_status",
        ),
    ]
