# Generated by Django 4.2.3 on 2024-07-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_opt_in",
            field=models.BooleanField(default=False, verbose_name="이메일 수신 동의"),
        ),
    ]
