# Generated by Django 4.2.3 on 2024-08-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_email_opt_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_day",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="출생일"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_month",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="출생월"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="출생년도"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "남자"), ("F", "여자")],
                max_length=1,
                null=True,
                verbose_name="성별",
            ),
        ),
    ]
