# Generated by Django 4.2.3 on 2024-08-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_birth_day_user_birth_month_user_birth_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=13, verbose_name="전화번호"),
        ),
    ]
