# Generated by Django 4.2.3 on 2025-02-01 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PassOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pass_order_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="가격"
                    ),
                ),
                (
                    "pass_order_pin_number",
                    models.CharField(max_length=4, verbose_name="핀 번호"),
                ),
                (
                    "pass_order_color",
                    models.CharField(max_length=2, verbose_name="색상"),
                ),
                (
                    "pass_order_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="주문날짜"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "주문요청"),
                            ("failed_payment", "결제실패"),
                            ("paid", "결제완료"),
                            ("prepared_product", "상품준비중"),
                            ("shipped", "배송중"),
                            ("delivered", "배송완료"),
                            ("cancelled", "주문취소"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=20,
                        verbose_name="진행상태",
                    ),
                ),
                (
                    "total_pages",
                    models.IntegerField(default=0, verbose_name="총 페이지 수"),
                ),
                (
                    "is_takeout",
                    models.BooleanField(default=False, verbose_name="테이크아웃 여부"),
                ),
                (
                    "pass_order_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자번호",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PassOrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        default=dict, editable=False, verbose_name="포트원 결제내역"
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="쇼핑몰 결제식별자",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="결제명")),
                (
                    "desired_amount",
                    models.PositiveIntegerField(
                        editable=False, verbose_name="결제금액"
                    ),
                ),
                (
                    "buyer_name",
                    models.CharField(
                        editable=False, max_length=100, verbose_name="구매자 이름"
                    ),
                ),
                (
                    "buyer_email",
                    models.EmailField(
                        editable=False, max_length=254, verbose_name="구매자 이메일"
                    ),
                ),
                (
                    "pay_method",
                    models.CharField(
                        choices=[("card", "신용카드")],
                        default="card",
                        max_length=20,
                        verbose_name="결제수단",
                    ),
                ),
                (
                    "pay_status",
                    models.CharField(
                        choices=[
                            ("ready", "결제 준비"),
                            ("paid", "결제 완료"),
                            ("cancelled", "결제 취소"),
                            ("failed", "결제 실패"),
                        ],
                        default="ready",
                        max_length=20,
                        verbose_name="결제상태",
                    ),
                ),
                (
                    "is_paid_ok",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name="결제성공 여부",
                    ),
                ),
                (
                    "pass_order",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="passorder.passorder",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PassOrderFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pass_order_file", models.FileField(upload_to="pass_order_files/")),
                (
                    "pass_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="passorder.passorder",
                    ),
                ),
            ],
        ),
    ]
