# Generated by Django 4.2.3 on 2025-02-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passorder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passorder",
            name="pass_order_pin_number",
            field=models.CharField(max_length=16, verbose_name="핀 번호"),
        ),
    ]
