# Generated by Django 4.2.3 on 2025-05-16 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("passorder", "0002_alter_passorder_pass_order_pin_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "is_print",
                    models.BooleanField(default=False, verbose_name="인쇄 여부"),
                ),
                (
                    "log",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="로그"
                    ),
                ),
                (
                    "pass_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="passorder.passorder",
                        verbose_name="패스 주문",
                    ),
                ),
            ],
            options={
                "verbose_name": "인쇄 대기열",
                "verbose_name_plural": "인쇄 대기열",
            },
        ),
    ]
