# Generated by Django 4.2.3 on 2026-02-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passorder', '0003_printqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='passorder',
            name='pass_order_quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='출력 수량'),
        ),
        migrations.AddField(
            model_name='printqueue',
            name='pass_order_ip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='요청 IP'),
        ),
    ]
