# Generated by Django 4.2.3 on 2026-02-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passorder', '0004_passorder_pass_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printqueue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성 시각'),
        ),
        migrations.AlterField(
            model_name='printqueue',
            name='is_print',
            field=models.BooleanField(db_index=True, default=False, verbose_name='인쇄 여부'),
        ),
        migrations.AlterField(
            model_name='printqueue',
            name='log',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='로그'),
        ),
    ]
