# Generated by Django 4.2.3 on 2024-07-14 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='가격')),
                ('order_pw', models.CharField(max_length=4, verbose_name='비밀번호')),
                ('order_color', models.CharField(max_length=2, verbose_name='색상')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='주문날짜')),
                ('order_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자번호')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preprint.order')),
            ],
        ),
    ]
