# Generated by Django 4.2.3 on 2024-08-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preprint", "0002_order_status_orderpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="locker_number",
            field=models.IntegerField(
                blank=True,
                help_text="1~100 사이의 숫자",
                null=True,
                verbose_name="사물함 번호",
            ),
        ),
    ]
